### ISSUE TITLE
Interaction rewrite for 1.9

### ISSUE THREAD

**Issue by ShadedJon** [DevotedMC/Citadel#16]
Features:

Re-enable default group creation on join. Historically was Username or Username+1 until one was available. The code to make the default group probably still exists somewhere.

Allow reinforcement to the default group simply by hitting any block with a reinforcement material.

Allow fortification if reinforcement material is placed in the offhand (shield hand), blocks placed at that point are reinforced to the default group.

Turn /ctb on by default on log-in. Only allow it to be turned off in the extremely rare case someone wants it off.

Result? Now Citadel can be used by a new player with a single direction. Hit your chest with a stone block. Bam, reinforced. No seven step instruction needed.

For what a good majority of the players use Citadel for, this rewrite will let them fortify their house and reinforce their door and chest without using a single command.

**Comment by Maxopoly** [comment]
See https://github.com/Civcraft/NameLayer/commit/4d42a4fc8045017f0f2b632fe88ce5a334bc4469 for the NameLayer part of this.

**Comment by Maxopoly** [comment]
See https://github.com/Civcraft/Citadel/pull/180 for the Citadel part of this

**Comment by ShadedJon** [comment]
I officially love you.

@ProgrammerDan let me know when this can go up on test server. I'll test it out with a couple new alts.

**Comment by ProgrammerDan** [comment]
Ok. Might be a day or two, pretty wiped out by IRL.

**Comment by ShadedJon** [comment]
np bb.

Good luck with IRL stuff ;)
