### ISSUE TITLE
[SOLVED] Error upon executing /cti

### ISSUE THREAD

**Issue by SlayG** [DevotedMC/Citadel#18]
Pretty new to the plugin, but I am 100% certain all database connections are good.

http://pastebin.com/NQwYG6Zd

Possibly related:
http://pastebin.com/sS22nwA9

**Comment by SlayG** [comment]
Also getting this now:

"[Citadel] Utility createNaturalReinforcement called with null"

It gets spammed about 15-30 times in a row on average

**Comment by Maxopoly** [comment]
Both of those are happening because your mysql version is very outdated. Either update that or use mariadb instead. Also after updating wipe your database to ensure that all tables are recreated properly.

**Comment by SlayG** [comment]
You rock my friend, I had no idea I was still on 5.5 O_O
