### ISSUE TITLE
Can still open chests while not on the group anymore

### ISSUE THREAD

**Issue by SearedOriginal** [DevotedMC/Citadel#23]
So I made a group, and then I left it. I opened a reinforced chest, and could still open it, even though someone else was owner of the group, and I wasn't apart of the group at all on /nl

**Comment by Aleksey-Terzi** [comment]
I've tested both on live Devoted and on my local environment following scenarios:

- Someone reinforced chest with his group - I cannot open chest

- I've reinforced chest with my own group and then leave it -  I cannot open chest

If you reproduced this bug on your local server - then please provide details about versions of used plugins and server.
If you has problem on live Devoted - then please provide "bad chest" cords and IGN of who experienced this problem.

**Comment by redmag3** [comment]
Was it a double chest? they can be reinforced to two groups simultaneously.

**Comment by searedOG** [comment]
It was a double chest. And no one was on the group that could reinforce to any groups I'm apart of

**Comment by redmag3** [comment]
hmm and there was no chance you did a /ctr to one half to be on a group you owned before you were removed?

**Comment by searedOG** [comment]
Nope, I wasn't on the group when the group moved to where they were.

**Comment by ProgrammerDan** [comment]
Has this ever been reproduced? If it has, please reopen.
