### ISSUE TITLE
Extreme Lag

### ISSUE THREAD

**Issue by 3ssej** [DevotedMC/Citadel#48]
Hello,
Sorry to bother you again, but I'm having some issues with Citadel.
For some reason, with Citadel installed, my server's TPS drops to about 13. Without it installed, everything is fine.
Timings with Citadel: https://timings.spigotmc.org/?url=metihufoka
Timings without Citadel: https://timings.spigotmc.org/?url=yitidocavi
(Specifically, look under "world - syncChunkLoad")
Does this have something to do with my MySQL database, or is there a configuration setting I'm missing?
I'm using the latest build from https://build.devotedmc.com/job/Citadel-master/.
Any help is appreciated.
Thanks,
Jesse

**Comment by ProgrammerDan** [comment]
Can you share your configuration, with passwords and usernames (and hosts) removed? I suspect this is caching related. Citadel performs very poorly if the cache is small; if the database host is not "very near" in latency terms to the server, or if the Database is IOPs bound.

**Comment by 3ssej** [comment]
Configuration: https://pastebin.com/LNSYgKMp
At first, when it started lagging I tried using [this](https://github.com/CivClassic/Configs/blob/master/Citadel/config.yml) configuration to see if it would fix anything, then I made the autosave interval much larger.

**Comment by ProgrammerDan** [comment]
The database is local or on a different host? Is this an SSD, NVMe, or spindisk IO? Network attached disk or physically attached? Available System memory? How much allocated to database?

**Comment by 3ssej** [comment]
The database is on a different (free for testing purposes) host due to the fact that the database that they provided didn't work.
I'm not sure what they use as far as storage. I'm currently using https://db4free.net/ to get things set up (and I plan on purchasing a database relatively soon)
I'm not sure if it's a network or physically attached disk, or what the available system memory/allocated memory is (although they just state that they will clear your database if you use more than 200 MB)
Sorry for the lack of information. I'm going to purchase a database (most likely) within the next few hours, so if you think it is a database issue, let me know and I'll get right to purchasing another database and updating you accordingly.

**Comment by ProgrammerDan** [comment]
I think it's a latency issue. A network connected database is going to have request/respond (RTT) cycles on the order of 50-150ms for every query... this means Citadel will be pausing for 50-150ms in some cases while filling its cache, or under certain typical usecases. It's not well optimized for a network attached database system.

I recommend finding a hosting platform that has a solid server (to run MC)  with a solid database offering under the same roof (same physical rack in the datacenter, or on a high speed interconnect -- < 10ms ) or on the same physical host, to avoid significant performance issues both now and later.

**Comment by 3ssej** [comment]
Yeah, I think that's what I'm going to end up doing. Thanks for your help thus far.

**Comment by ProgrammerDan** [comment]
Ok, I'll leave this open for now, unless you want me to close.

**Comment by 3ssej** [comment]
I switched hosts and got a database located right next to the node I am on, and it seems to have fixed the issue.
Thanks for all your help, I'm going to close this now.

**Comment by ProgrammerDan** [comment]
Thanks for the update, great news!
