### ISSUE TITLE
Orebfuscator + citadel reinforcement bypass

### ISSUE THREAD

**Issue by iNko97** [DevotedMC/Citadel#54]
Clicking a locked chest that is still orebfuscated with food in hand, and offhand empty, lets me open it?

Set orebfuscator distance to 2 for easier testing.

**Comment by ProgrammerDan** [comment]
Orebfuscator impact is visual _only_ -- it only changes what you see, but doesn't change any blocks?

**Comment by iNko97** [comment]
That's the way it should be (And probably is), as I did not modify the plugin itself.
Right clicking the inventory while it still is orebfuscated with non-consumables (Torch, Cobblestone...) blocks the interactEvent correctly.

How can I go on troubleshooting this better?

**Comment by ProgrammerDan** [comment]
Complex, interesting. I wonder if in later versions a different "event" is sourced at client due to different block? 

Does the chest have a full inventory as you'd expect? Can you confirm same behavior for another player under same conditions? 

I'm struggling to even think how to approach this since there is no block change server side, only way this would legitimately happen is if the server is altering its behavior based on the client's "perception" of a block, which is _insanely bad design_ on Minecraft's side but cannot be ruled out....

Most likely would need some kind of event dump infras to see what is happening differently between the several states, specifically:

1) Unobfuscated, click with food

2) Unobfuscated, click with non-food.

3) Obfuscated, click with food

4) Obfuscated, click with non-food

and right click vs. left click variations to see what the hell is going on there...

**Comment by iNko97** [comment]
Right clicks only, as left click does not open chests, just hits them.

1. Unobfuscated, click with food:
 a. Nothing in offhand: Blocked
 b. Block in offhand: Blocked 
 c. Food in offhand: Blocked
2. Unobfuscated, click with non consumable:
 a. Nothing in offhand: Blocked
 b. Block in offhand: Blocked
 c. Food in offhand: Blocked
3. Unobfuscated, click with empty hand:
 a. Nothing in offhand: Blocked
 b. Block in offhand: Blocked
 c. Food in offhand: Blocked

1. Obfuscated, click with food:
 a. Nothing in offhand: Opens, says CHEST IS LOCKED! I can interact and edit contents.
 b. Block in offhand:  Blocked
 c. Food in offhand: Blocked
2. Obfuscated, click with non consumable:
 a. Nothing in offhand: Blocked
 b. Block in offhand: Blocked
 c. Food in offhand: Blocked
3. Obfuscated, click with empty hand:
 a. Nothing in offhand: Opens, says CHEST IS LOCKED! I can interact and edit contents.
 b. Block in offhand: Opens, says CHEST IS LOCKED! I can interact and edit contents.
 c. Food in offhand: Opens, says CHEST IS LOCKED! I can interact and edit contents.

**Comment by iNko97** [comment]
What I think happens is double interactions because of offhand.

**Comment by ProgrammerDan** [comment]
> What I think happens is double interactions because of offhand.

This is an interesting theory. AFAIK there is no provision in the locking code to allow a bypass regardless, but I wonder if spigot has a bug where the event simply isn't being generated to _be_ cancelled? I wonder. Or cancel ignored?

**Comment by ProgrammerDan** [comment]
Bah, interesting. Errors should not allow bypass, something must not be handling null correctly...

**Comment by iNko97** [comment]
I seem to have fixed the problem!

Something weird was happening with offhand, doing an additional checks for reinforced inventories when the event is called with offhand fixed it. 
I still return the event if the original condition is met later because letting more events through could break the following code.

`try {
			if (!pie.hasBlock() || (pie.getHand() != EquipmentSlot.HAND && pie.getHand() != EquipmentSlot.OFF_HAND)){
				return;
			}

			Player player = pie.getPlayer();
			Block block = Utility.getRealBlock(pie.getClickedBlock());
			Reinforcement generic_reinforcement = rm.getReinforcement(block);
			PlayerReinforcement reinforcement = null;
			if (generic_reinforcement instanceof PlayerReinforcement) {
				reinforcement = (PlayerReinforcement) generic_reinforcement;
			}

			Action action = pie.getAction();
			boolean access_reinforcement = action == Action.RIGHT_CLICK_BLOCK
					&& reinforcement != null && reinforcement.isSecurable();
			boolean normal_access_denied = reinforcement != null
					&& ((reinforcement.isDoor() && !reinforcement
							.canAccessDoors(player)) || (reinforcement
							.isContainer() && !reinforcement
							.canAccessChests(player)));
			boolean admin_can_access = player.hasPermission("citadel.admin");
			if (access_reinforcement && normal_access_denied
					&& !admin_can_access) {
				/*
				 * Citadel.verbose( VerboseMsg.ReinLocked,
				 * player.getDisplayName(), block.getLocation().toString());
				 */
				pie.getPlayer().sendMessage(
						ChatColor.RED
								+ String.format("%s e' bloccato", block.getType()
										.name()));
				pie.setCancelled(true);
			}
			// Not really sure what this is for. Should come up in testing.
			/*
			 * else if (action == Action.PHYSICAL) { AccessDelegate
			 * aboveDelegate =
			 * AccessDelegate.getDelegate(block.getRelative(BlockFace.UP)); if
			 * (aboveDelegate instanceof CropAccessDelegate &&
			 * aboveDelegate.isReinforced()) { Citadel.verbose(
			 * VerboseMsg.CropTrample, block.getLocation().toString());
			 * pie.setCancelled(true); } }
			 */
			if (pie.isCancelled())
				return;

			if (!pie.hasBlock() || pie.getHand() != EquipmentSlot.HAND){
				return;
			}`

Testing follows:

Obfuscated, click with food:
a. Nothing in offhand: Blocked (Double CHEST is blocked message appears)
b. Block in offhand: Blocked
c. Food in offhand: Blocked

Obfuscated, click with empty hand:
a. Nothing in offhand: Blocked (Double CHEST is blocked message appears)
b. Block in offhand: Blocked (Double CHEST is blocked message appears)
c. Food in offhand: Blocked (Double CHEST is blocked message appears)

Yay!

**Comment by ProgrammerDan** [comment]
Awesome news! Any chance you can check with single chest and half
obfuscated double chest, just to be sure? Looking forward to the PR. Great
work.

**Comment by iNko97** [comment]
Full obfuscated chest and half obfuscated chest get blocked correctly.

**Comment by ProgrammerDan** [comment]
Amazing.

**Comment by ProgrammerDan** [comment]
Fixed by #55
